### PR TITLE
Cleanup CMakeLists.txt with ament_cmake_auto

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by wep21** [comment]
@clalancette Could you also review this?

**Review by hidmic — APPROVED** [review]
I don't have a strong opinion in favor or against `ament_cmake_auto`, but local inspection of the `install` directory shows no difference between both approaches so I'm OK with it.

@paulbovbel thoughts?

**Comment by wep21** [comment]
@paulbovbel friendly ping

**Comment by wep21** [comment]
@hidmic @paulbovbel friendly ping

**Comment by hidmic** [comment]
@wep21 I've re-targeted this PR to the `rolling` branch. We can backport to Galactic / Foxy once this is in. Testing it locally...

**Comment by hidmic** [comment]
Builds locally just fine. Going in! Thanks for the patience @wep21.

**Pull request merged**
