### PR TITLE
Update package maintainers.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says.

### CODE REVIEW

**Comment by hidmic** [comment]
@paulbovbel I've been assigned to help you out with repo maintainership here (for both ROS and ROS 2 branches). Let me know if you want to split the load in any particular way.

**Comment by paulbovbel** [comment]
> I've been assigned to help you out with repo maintainership here (for both ROS and ROS 2 branches). Let me know if you want to split the load in any particular way.

Thanks, I've definitely lapsed in my maintainership. Any particular issues on this package specifically?

**Comment by hidmic** [comment]
> Any particular issues on this package specifically?

Oh, no, I didn't mean I'm here to push for anything in particular. Just stepping up to help maintain. CC @clalancette.

**Review by paulbovbel — APPROVED** [review]

**Comment by hidmic** [comment]
Noetic jobs show CMake warnings. We should get it fixed.

**Pull request merged**
